In [180]:
import pandas as pd

In [181]:
df = pd.read_csv("Data/matches.csv")

In [182]:
df.sample()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
28,29,"April 19, 2026","New PCA Cricket Stadium, Mullanpur",PBKS,LSG,League,LSG,Bowl,254.0,7.0,...,PBKS,54.0,NaN,0.0,Priyansh Arya,Priyansh Arya,93.0,Prince Yadav,2--25,No

In [183]:
df.sample(2)

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
20,21,"April 13, 2026","Rajiv Gandhi International Stadium, Hyderabad",SRH,RR,League,RR,Bowl,216.0,6.0,...,SRH,57.0,NaN,6.0,Praful Hinge,Ishan Kishan,91.0,Sakib Hussain,4--24,No
36,37,"April 26, 2026","Narendra Modi Stadium, Ahmedabad",GT,CSK,League,GT,Bowl,158.0,7.0,...,GT,NaN,8.0,20.0,Kagiso Rabada,Sai Sudarshan,87.0,Kagiso Rabada,3--25,No

In [184]:
df.head(5) # shows staring rows

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
0,1,"March 28, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,SRH,League,RCB,Bowl,201.0,9.0,...,RCB,NaN,6.0,26.0,Jacob Duffy,Ishan Kishan,80.0,Jacob Duffy,3--22,No
1,2,"March 29, 2026","Wankhede Stadium, Mumbai",MI,KKR,League,MI,Bowl,220.0,4.0,...,MI,NaN,6.0,5.0,Shardul Thakur,Ryan Rickelton,81.0,Shardul Thakur,3--39,No
2,3,"March 30, 2026","Barsapara Stadium, Guwahati",RR,CSK,League,RR,Bowl,127.0,10.0,...,RR,NaN,8.0,47.0,Nandre Burger,Vaibhav Sooryavanshi,52.0,Jofra Archer,2--19,No
3,4,"March 31, 2026","New PCA Cricket Stadium, Mullanpur",PBKS,GT,League,PBKS,Bowl,162.0,6.0,...,PBKS,NaN,3.0,5.0,Cooper Connolly,Cooper Connolly,72.0,Prasidh Krishna,3--29,No
4,5,"April 01, 2026","Ekana Cricket Stadium, Lucknow",LSG,DC,League,DC,Bowl,141.0,10.0,...,DC,NaN,6.0,17.0,Sameer Rizvi,Sameer Rizvi,70.0,Lungi Ngidi,3--27,No

In [185]:
df.tail(5) # shows last rows

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
34,35,"April 25, 2026","Arun Jaitley Stadium, Delhi",DC,PBKS,League,DC,Bat,264.0,2.0,...,PBKS,NaN,6.0,7.0,KL Rahul,KL Rahul,152.0,Kuldeep Yadav,2--46,No
35,36,"April 25, 2026","Sawai Mansingh Stadium, Jaipur",RR,SRH,League,SRH,Bowl,228.0,6.0,...,SRH,NaN,5.0,9.0,Ishan Kishan,Vaibhav Sooryavanshi,103.0,Jofra Archer,2--34,No
36,37,"April 26, 2026","Narendra Modi Stadium, Ahmedabad",GT,CSK,League,GT,Bowl,158.0,7.0,...,GT,NaN,8.0,20.0,Kagiso Rabada,Sai Sudarshan,87.0,Kagiso Rabada,3--25,No
37,38,"April 26, 2026","Ekana Cricket Stadium, Lucknow",LSG,KKR,League,LSG,Bowl,155.0,7.0,...,KKR,NaN,NaN,5.0,Rinku Singh,Rinku Singh,83.0,Mohsin Khan,5--23,Yes
38,39,"April 27, 2026","Arun Jaitley Stadium, Delhi",DC,RCB,League,RCB,Bowl,75.0,10.0,...,RCB,NaN,9.0,81.0,Josh Hazlewood,Devdutt Padikkal,34.0,Josh Hazlewood,4--12,No

In [186]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             39 non-null     int64
 1   date                 39 non-null     object
 2   venue                39 non-null     object
 3   team1                39 non-null     object
 4   team2                39 non-null     object
 5   stage                39 non-null     object
 6   toss_winner          39 non-null     object
 7   toss_decision        39 non-null     object
 8   first_ings_score     38 non-null     float64
 9   first_ings_wkts      38 non-null     float64
 10  second_ings_score    38 non-null     float64
 11  second_ings_wkts     38 non-null     float64
 12  match_result         39 non-null     object
 13  match_winner         38 non-null     object
 14  wb_runs              15 non-null     float64
 15  wb_wickets           22 non-null     float64
 16  balls_left           38 non-null     float64
 17  player_of_the_match  38 non-null     object
 18  top_scorer           38 non-null     object
 19  highscore            38 non-null     float64
 20  best_bowling         38 non-null     object
 21  best_bowling_figure  38 non-null     object
 22  super_over_match     39 non-null     object
dtypes: float64(8), int64(1), object(14)
memory usage: 7.1+ KB

In [187]:
#df.isnull() # when find null value say true & when not find null value the say false

In [188]:
df.isnull().sum()

match_id                0
date                    0
venue                   0
team1                   0
team2                   0
stage                   0
toss_winner             0
toss_decision           0
first_ings_score        1
first_ings_wkts         1
second_ings_score       1
second_ings_wkts        1
match_result            0
match_winner            1
wb_runs                24
wb_wickets             17
balls_left              1
player_of_the_match     1
top_scorer              1
highscore               1
best_bowling            1
best_bowling_figure     1
super_over_match        0
dtype: int64

In [189]:
# find percentage of every column having null value
df.isnull().sum()/len(df)*100

match_id                0.000000
date                    0.000000
venue                   0.000000
team1                   0.000000
team2                   0.000000
stage                   0.000000
toss_winner             0.000000
toss_decision           0.000000
first_ings_score        2.564103
first_ings_wkts         2.564103
second_ings_score       2.564103
second_ings_wkts        2.564103
match_result            0.000000
match_winner            2.564103
wb_runs                61.538462
wb_wickets             43.589744
balls_left              2.564103
player_of_the_match     2.564103
top_scorer              2.564103
highscore               2.564103
best_bowling            2.564103
best_bowling_figure     2.564103
super_over_match        0.000000
dtype: float64

In [190]:
# hint
df["team1"].unique()
rcb = df["team1"]=="RCB"

In [191]:
df[rcb]

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
0,1,"March 28, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,SRH,League,RCB,Bowl,201.0,9.0,...,RCB,NaN,6.0,26.0,Jacob Duffy,Ishan Kishan,80.0,Jacob Duffy,3--22,No
10,11,"April 05, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,CSK,League,CSK,Bowl,250.0,3.0,...,RCB,43.0,NaN,2.0,Tim David,Tim David,70.0,Bhuvneshwar Kumar,3--41,No
22,23,"April 15, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,LSG,League,RCB,Bowl,146.0,10.0,...,RCB,NaN,5.0,29.0,Josh Hazlewood,Virat Kohli,49.0,Rasikh Salam,4--24,No
25,26,"April 18, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,DC,League,DC,Bowl,175.0,8.0,...,DC,NaN,6.0,1.0,Tristan Stubbs,Phil Salt,63.0,Bhuvneshwar Kumar,3--26,No
33,34,"April 24, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,GT,League,RCB,Bowl,205.0,3.0,...,RCB,NaN,5.0,7.0,Virat Kohli,Sai Sudarshan,100.0,Rashid Khan,2--49,No

In [ ]:
#df=df.drop(columns=["wb_runs","wb_wickets"])

In [193]:
df.columns[df.isnull().any()]

Index(['first_ings_score', 'first_ings_wkts', 'second_ings_score',
       'second_ings_wkts', 'match_winner', 'balls_left', 'player_of_the_match',
       'top_scorer', 'highscore', 'best_bowling', 'best_bowling_figure'],
      dtype='object')

In [194]:

df.isnull().sum()

match_id               0
date                   0
venue                  0
team1                  0
team2                  0
stage                  0
toss_winner            0
toss_decision          0
first_ings_score       1
first_ings_wkts        1
second_ings_score      1
second_ings_wkts       1
match_result           0
match_winner           1
balls_left             1
player_of_the_match    1
top_scorer             1
highscore              1
best_bowling           1
best_bowling_figure    1
super_over_match       0
dtype: int64

In [195]:
df[df.isnull().any(axis=1)]

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,second_ings_wkts,match_result,match_winner,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
11,12,"April 06, 2026","Eden Gardens, Kolkata",KKR,PBKS,League,KKR,Bat,NaN,NaN,...,NaN,abandoned,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No

In [196]:
df = df.dropna()

In [197]:
df.isnull().sum()

match_id               0
date                   0
venue                  0
team1                  0
team2                  0
stage                  0
toss_winner            0
toss_decision          0
first_ings_score       0
first_ings_wkts        0
second_ings_score      0
second_ings_wkts       0
match_result           0
match_winner           0
balls_left             0
player_of_the_match    0
top_scorer             0
highscore              0
best_bowling           0
best_bowling_figure    0
super_over_match       0
dtype: int64

In [198]:
df.columns

Index(['match_id', 'date', 'venue', 'team1', 'team2', 'stage', 'toss_winner',
       'toss_decision', 'first_ings_score', 'first_ings_wkts',
       'second_ings_score', 'second_ings_wkts', 'match_result', 'match_winner',
       'balls_left', 'player_of_the_match', 'top_scorer', 'highscore',
       'best_bowling', 'best_bowling_figure', 'super_over_match'],
      dtype='object')

In [199]:
df['venue'].value_counts()

venue
M. Chinnaswamy Stadium, Bangalore                5
Wankhede Stadium, Mumbai                         4
Ekana Cricket Stadium, Lucknow                   4
Narendra Modi Stadium, Ahmedabad                 4
Rajiv Gandhi International Stadium, Hyderabad    4
Arun Jaitley Stadium, Delhi                      4
Barsapara Stadium, Guwahati                      3
MA Chidambaram Stadium, Chennai                  3
Eden Gardens, Kolkata                            3
New PCA Cricket Stadium, Mullanpur               3
Sawai Mansingh Stadium, Jaipur                   1
Name: count, dtype: int64

In [200]:
df['match_winner'].value_counts()

match_winner
RCB     6
PBKS    6
SRH     5
RR      4
GT      4
DC      3
CSK     3
LSG     3
MI      2
KKR     2
Name: count, dtype: int64

In [201]:
df['match_winner']

0      RCB
1       MI
2       RR
3     PBKS
4       DC
5      SRH
6     PBKS
7       DC
8       RR
9      LSG
10     RCB
12      RR
13      GT
14     LSG
15      RR
16    PBKS
17     CSK
18      GT
19     RCB
20     SRH
21     CSK
22     RCB
23    PBKS
24      GT
25      DC
26     SRH
27     KKR
28    PBKS
29      MI
30     SRH
31     LSG
32     CSK
33     RCB
34    PBKS
35     SRH
36      GT
37     KKR
38     RCB
Name: match_winner, dtype: object

In [202]:
df.describe()

,match_id,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,balls_left,highscore
count,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000
mean,20.210526,190.526316,6.289474,175.500000,6.052632,10.684211,79.447368
std,11.477729,39.394565,2.470451,39.747684,2.670635,15.773918,24.521031
min,1.000000,75.000000,2.000000,77.000000,1.000000,0.000000,34.000000
25%,10.250000,159.750000,4.250000,159.250000,4.000000,0.250000,60.750000
50%,20.500000,197.000000,6.000000,180.000000,5.000000,6.000000,77.500000
75%,29.750000,215.000000,8.000000,203.750000,8.000000,12.000000,91.750000
max,39.000000,264.000000,10.000000,265.000000,10.000000,81.000000,152.000000

In [203]:
# Duplicates
#df.drop_duplicte()